# Generated by Django 4.0.5 on 2022-06-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=250, unique=True, verbose_name='Apellido')),
                ('puntos', models.PositiveIntegerField(unique=True, verbose_name='Puntos')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
                ('puntos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, unique=True, verbose_name='Apellido')),
                ('DNI', models.PositiveIntegerField(unique=True, verbose_name='DNI')),
                ('NombreEquipo', models.CharField(max_length=50, unique=True, verbose_name='Nombre Equipo')),
                ('fecha_naciemiento', models.DateField(verbose_name='Fecha de Naciemiento')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.persona', verbose_name='Liga General')),
                ('puntos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.partido', verbose_name='Puntos Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('jugadores', models.ManyToManyField(to='Proyecto.jugador')),
            ],
        ),
    ]
