# Generated by Django 4.0.5 on 2022-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_alter_equipo_nombre_alter_jugador_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='puntos',
            field=models.PositiveIntegerField(unique=True, verbose_name='PuntosObjetos'),
        ),
    ]
