# Generated by Django 4.0.5 on 2022-06-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_alter_objeto_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contra',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='Contraseña'),
        ),
    ]
