# Generated by Django 4.0.5 on 2022-07-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_persona_contra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='NombreEquipo',
            field=models.CharField(max_length=100, unique=True, verbose_name='NombreEquipo'),
        ),
    ]
