# Generated by Django 4.0.5 on 2022-07-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0005_alter_persona_nombreequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_naciemiento',
        ),
    ]
