# Generated by Django 4.0.5 on 2022-07-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0006_remove_persona_fecha_naciemiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='puntos',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='puntos',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='DNI',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='NombreEquipo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='contra',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
