# Generated by Django 4.0.5 on 2022-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0009_equipo_puntos_alter_liga_puntos_delete_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liga',
            name='publico',
        ),
        migrations.AlterField(
            model_name='liga',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
